<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="airecommendationsystem"
    nsURI="http://www.example.org/airecommendationsystem" nsPrefix="airs">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rating">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//Content"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recommendation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendedContent" eType="#//Content"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predictedRating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explanation" eType="#//Explanation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Explanation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ExplanationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factors" upperBound="-1"
        eType="#//ExplanationFactor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplanationFactor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" derived="true" volatile="true" transient="true">
	  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
		<details key="derivation" value="self.value.abs() / self.oclContainer().oclAsType(Explanation).factors->collect(value.abs())->sum()"/>
	  </eAnnotations>
	</eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AIRecommendationEngine">
    <eOperations name="predictAndExplain" eType="#//Recommendation">
      <eParameters name="user" eType="#//User"/>
      <eParameters name="content" eType="#//Content"/>
    </eOperations>
    <eOperations name="trainModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentCatalog" upperBound="-1"
        eType="#//Content" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ratings" upperBound="-1"
        eType="#//Rating" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aiModel" eType="#//AIModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracer" eType="#//AIModelTracer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AIModel">
    <eOperations name="fit">
      <eParameters name="ratingMatrix" eType="#//RatingMatrix"/>
    </eOperations>
    <eOperations name="predict" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eParameters name="userIdx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="contentIdx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="extractFactors" eType="#//Vector">
      <eParameters name="userIdx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="contentIdx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExplainable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AIModelTracer">
    <eOperations name="tracePrediction">
      <eParameters name="user" eType="#//User"/>
      <eParameters name="content" eType="#//Content"/>
      <eParameters name="recommendation" eType="#//Recommendation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//PredictionTrace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RatingMatrix" instanceClassName="java.util.List"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Vector" instanceClassName="java.util.List"/>
  <eClassifiers xsi:type="ecore:EClass" name="PredictionTrace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predictedRating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explanation" eType="#//Explanation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExplanationType">
    <eLiterals name="FACTOR_BASED"/>
    <eLiterals name="CONTENT_BASED" value="1"/>
    <eLiterals name="COLLABORATIVE" value="2"/>
  </eClassifiers>
</ecore:EPackage>